### PR TITLE
DalliStore compatibility for single sign out functionality

### PR DESCRIPTION
**Pull request by Slotos**

### CODE REVIEW

**Comment by Slotos** [comment]
Just noticed you mentioning a complete rewrite. Closing pull request, this functionality can be implemented in personal middleware for now. Also needs a bit polishing (i.e. class comparison when there's no such constant).

**Comment by Slotos** [comment]
Tested this code with dalli, cookie and redis stores in middleware implementation. Everything behaves as intended.

**Comment by elspethsoup** [comment]
@Slotos, thanks so much for this contribution! The issue is testing it. As I'm sure you are aware, the tests on the greatest. Even if I don't end up merging this directly, you have inspired solutions to some of the refactoring quandaries I've been having.

**Comment by Slotos** [comment]
I'm glad I could provide some insights.

I'll close the pull request now, since it mostl likely won't fit the new version

**Pull request closed without merging**
