### PR TITLE
Compatibility with rubycas-client version 2.3.5

### PR DESCRIPTION
**Pull request by thegekko**
Many modifications were made to 2.3.5 or rubycas-client which are breaking compatibility with this one. I retroffited all changes made into this patch.

Tested on my project using rubycas-client on rails 3.1.1.

My first patch on github...

### CODE REVIEW

**Comment by brodock** [comment]
+1 to get it solved

**Comment by elspethsoup** [comment]
I'll take a look at this soon and hopefully get an update out this weekend. Thanks for the patch!

**Comment by mazondo** [comment]
I'd like to throw my hat in the ring as a +1 for solving this as well.

**Comment by elspethsoup** [comment]
Hey all, sorry it has taken so long for me to get to. I have been sick for about a month now and hope to get to it soon.

**Comment by fosrias** [comment]
+1 To just merge the patch!

**Comment by zuk** [comment]
Do we have confirmation that this works as-is? If so, can someone clean it up and re-submit? All the commented out code and whitespace inconsistencies are making my eyes bleed.

**Comment by shellac** [comment]
I can confirm that this is working (rails 3.2.1 project). Merge it (doesn't need much cleaning).

**Comment by zuk** [comment]
Thanks! Merged.

**Pull request merged**
